/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *Jacob L
 * Oct 10, 2018
 * Uses a java GUI to allow you to order a putrid pizza (according to specifications) 
 */

//Imports ALL text cause I feel like it
import java.text.*;

public class MakingAPizza extends javax.swing.JFrame {

    
    /**
     * Creates new form MakingAPizza
     */
    public MakingAPizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        diameterInputLabel = new javax.swing.JLabel();
        diameterInputField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        secondaryBackgroundPanel = new javax.swing.JPanel();
        subtotalLabel = new javax.swing.JLabel();
        taxesField = new javax.swing.JTextField();
        subtotalField = new javax.swing.JTextField();
        grandtotalField = new javax.swing.JTextField();
        outputJokeLabel = new javax.swing.JLabel();
        grandtotalLabel = new javax.swing.JLabel();
        taxesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(195, 234, 154));

        titleLabel.setFont(new java.awt.Font("Wet Pet", 0, 48)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Putrid Pizza Dot Net");

        diameterInputLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        diameterInputLabel.setText("Diameter Of Pizza (CM) :");

        calculateButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        calculateButton.setText("CALCULATE");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        secondaryBackgroundPanel.setBackground(new java.awt.Color(227, 182, 72));
        secondaryBackgroundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        subtotalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subtotalLabel.setText("SUBTOTAL ($) :");

        taxesField.setEditable(false);
        taxesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxesFieldActionPerformed(evt);
            }
        });

        subtotalField.setEditable(false);
        subtotalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalFieldActionPerformed(evt);
            }
        });

        grandtotalField.setEditable(false);
        grandtotalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grandtotalFieldActionPerformed(evt);
            }
        });

        outputJokeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        grandtotalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        grandtotalLabel.setText("GRANDTOTAL ($) :");

        taxesLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        taxesLabel.setText("TAXES ($) :");

        javax.swing.GroupLayout secondaryBackgroundPanelLayout = new javax.swing.GroupLayout(secondaryBackgroundPanel);
        secondaryBackgroundPanel.setLayout(secondaryBackgroundPanelLayout);
        secondaryBackgroundPanelLayout.setHorizontalGroup(
            secondaryBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondaryBackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(secondaryBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subtotalLabel)
                    .addComponent(grandtotalLabel)
                    .addComponent(taxesLabel))
                .addGap(10, 10, 10)
                .addGroup(secondaryBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taxesField)
                    .addComponent(subtotalField)
                    .addComponent(grandtotalField))
                .addGap(18, 18, 18))
            .addComponent(outputJokeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        secondaryBackgroundPanelLayout.setVerticalGroup(
            secondaryBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondaryBackgroundPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(secondaryBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotalLabel))
                .addGap(37, 37, 37)
                .addGroup(secondaryBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxesLabel))
                .addGap(43, 43, 43)
                .addGroup(secondaryBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grandtotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grandtotalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(outputJokeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(4);
        jTextArea1.setText("Please input the size of the\npizza you want. Numbers only\nplease. Size 16-19cm are\nnot avalible. ");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diameterInputLabel)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                .addComponent(calculateButton)
                                .addGap(14, 14, 14)))
                        .addComponent(diameterInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(secondaryBackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diameterInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diameterInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(secondaryBackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taxesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxesFieldActionPerformed

    private void subtotalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalFieldActionPerformed

    private void grandtotalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grandtotalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grandtotalFieldActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        //THE ACTION IS ALL SET UP HERE
        
        //declare decimal format
        DecimalFormat money = new DecimalFormat ("###0.00");
        
        //declare Variables
        double diameterRequested = Double.parseDouble(diameterInputField.getText());
        final double DIAMETER_COST = 0.50;//per diameter
        final double ADDITIONAL_COSTS = 0.99 + 0.75;//Labour and Rent Costs
        final double HST = 0.13;//13%
        double subtotal;
        double taxtotal;
        double grandtotal;
        
        //algorithms
        subtotal = diameterRequested * DIAMETER_COST + ADDITIONAL_COSTS;
        taxtotal = subtotal * HST;
        grandtotal = subtotal + taxtotal;
        
        //output Cost
        subtotalField.setText(""+money.format(subtotal));
        taxesField.setText(""+money.format(taxtotal));
        grandtotalField.setText(""+money.format(grandtotal));
        
        //output Jokes
        //outputJokeLabel.setText(""+money.format(grandtotal));
        if (diameterRequested >=1 && diameterRequested <=15) {
            outputJokeLabel.setText("We are going to make you a cute little pizza!");
        }
        else if (diameterRequested >=20 && diameterRequested <40){
            outputJokeLabel.setText("This will be delicious!");
        }
        else if (diameterRequested >40){
            outputJokeLabel.setText("Whoa, big pizza! You might need a truck to get this home");
        }
        else {
            outputJokeLabel.setText("This is an documented feature, not a bug");
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakingAPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakingAPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakingAPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakingAPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakingAPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JTextField diameterInputField;
    private javax.swing.JLabel diameterInputLabel;
    private javax.swing.JTextField grandtotalField;
    private javax.swing.JLabel grandtotalLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel outputJokeLabel;
    private javax.swing.JPanel secondaryBackgroundPanel;
    private javax.swing.JTextField subtotalField;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JTextField taxesField;
    private javax.swing.JLabel taxesLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
